
services:
    rundum_event_bundle.maker.make_entity_events:
        class: Rundum\EventBundle\Maker\MakeEntityEvents
        autowire: true
        arguments:
            - '@maker.doctrine_helper'
        tags:
            - 'maker.command'

    Rundum\EventBundle\Maker\MakeEntityEvents: '@rundum_event_bundle.maker.make_entity_events'
    # rundum_symfony_helper_bundle.data_list_service:
    #     class: Rundum\SymfonyHelperBundle\Service\DataListService
    #     autowire: false
    #     arguments:
    #         - '@twig'
    #         - '@form.factory'
    
    # Rundum\SymfonyHelperBundle\Service\DataListService: '@rundum_symfony_helper_bundle.data_list_service'      
    
    # rundum_symfony_helper_bundle.event_service:
    #     class: Rundum\SymfonyHelperBundle\Service\EventService
    #     autowire: false
    #     arguments:
    #         - '@event_dispatcher'
            
    # Rundum\SymfonyHelperBundle\Service\EventService: '@rundum_symfony_helper_bundle.event_service'