
services:
    rundum_event_bundle.maker.make_entity_events:
        class: Rundum\EventBundle\Maker\MakeEntityEvents
        autowire: true
        arguments:
            - '@maker.doctrine_helper'
        tags:
            - 'maker.command'

    Rundum\EventBundle\Maker\MakeEntityEvents: '@rundum_event_bundle.maker.make_entity_events'

    rundum_event_bundle.event_subscriber.entity_event_subscriber:
        class: Rundum\EventBundle\EventSubscriber\EntityEventSubscriber
        autowire: true
        arguments:
            - '@logger'
            - '@doctrine'
            - '@event_dispatcher'
        tags:
            - 'kernel.event_subscriber'

    Rundum\EventBundle\EventSubscriber\EntityEventSubscriber: '@rundum_event_bundle.event_subscriber.entity_event_subscriber'

when@test:
    services:
        rundum_event_bundle.maker.make_entity_events:
            class: Rundum\EventBundle\Maker\MakeEntityEvents
            public: true
            autowire: true
            arguments:
                - '@maker.doctrine_helper'
            tags:
                - 'maker.command'
