
services:
    rundum_event_bundle.maker.make_entity_events:
        class: Rundum\EventBundle\Maker\MakeEntityEvents
        autowire: true
        arguments:
            - '@maker.doctrine_helper'
        tags:
            - 'maker.command'

    Rundum\EventBundle\Maker\MakeEntityEvents: '@rundum_event_bundle.maker.make_entity_events'

when@test:
    services:
        rundum_event_bundle.maker.make_entity_events:
            class: Rundum\EventBundle\Maker\MakeEntityEvents
            public: true
            autowire: true
            arguments:
                - '@maker.doctrine_helper'
            tags:
                - 'maker.command'
